# Generated by Django 4.1.4 on 2022-12-20 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.author'),
            preserve_default=False,
        ),
    ]
