# Generated by Django 4.1.4 on 2022-12-20 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_book_authors_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=5),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.PositiveSmallIntegerField(default=1980, validators=[django.core.validators.MinValueValidator(1895), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
